server:
  port: 8082

spring:
  application:
    name: admin-service

  datasource:
    url: jdbc:h2:mem:admindb
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
