server:
  port: 8083

spring:
  application:
    name: email-service

mail:
  host: smtp.gmail.com
  port: 587
  username: your-email@gmail.com
  password: your-app-password
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
